Replace username

diff --git a/subcommands/zenlog-a2h-wrapper b/subcommands/zenlog-a2h-wrapper
--- a/subcommands/zenlog-a2h-wrapper
+++ b/subcommands/zenlog-a2h-wrapper
@@ -5,6 +5,6 @@
 a2h "$@"
 if (( $? == 127 )) ; then
     # See fzf-wrapper.
-    echo $'zenlog: A2H not found. Run this command to install: \e[1;33mgo get -u github.com/omakoto/a2h\e[0m' 1>&2
+    echo $'zenlog: A2H not found. Run this command to install: \e[1;33mgo get -u github.com/akawashiro/a2h\e[0m' 1>&2
     exit 1
 fi
